name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy code and Build on Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.STAGING_SERVER_IP }} << 'EOF_SERVER_OPS'

            if [ ! -d "app" ]; then
              git clone git@github.com:gibihu/gembulk.com.git app
            fi

            cd app

            git fetch origin main
            git reset --hard HEAD
            git clean -fd
            git pull origin main
            echo 'Git pull completed on server.'

            source /.nodevenv/versions/24/bin/
            echo 'Node.js virtual environment activated.'

            npm install --legacy-peer-deps || true
            echo 'Frontend dependencies installed on server.'

            npm run build
            echo 'Frontend assets built on server.'

            chmod -R 775 storage bootstrap/cache
            echo 'Permissions set completed on server.'

            php artisan storage:link
            echo 'Laravel storage:link executed on app/public.'

            rsync -avz --delete \
              --exclude 'index.php' \
              /app/public/ \
              /httpdocs/
            echo 'Public folder synced from app to httpdocs.'
            cat > /httpdocs/index.php << 'END'
          <?php

          use Illuminate\Foundation\Application;
          use Illuminate\Http\Request;

          define('LARAVEL_START', microtime(true));

          if (file_exists($maintenance = __DIR__.'/../app/storage/framework/maintenance.php')) {
              require $maintenance;
          }

          require __DIR__.'/../app/vendor/autoload.php';

          $app = require_once __DIR__.'/../app/bootstrap/app.php';

          $app->handleRequest(Request::capture());
          END
            echo 'Custom index.php created in httpdocs.'

            composer install
            php artisan migrate --force
            php artisan cache:clear
            php artisan config:clear
            php artisan route:clear
            php artisan view:clear
            composer dump-autoload


            echo 'Laravel Artisan commands executed on server.'
          EOF_SERVER_OPS

          echo 'Deploy completed.'
